import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Stethoscope } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Stepper } from "@/components/survey/Stepper";
import { ConsentData, ConsentStep } from "@/components/survey/ConsentStep";
import { EligibilityStep } from "@/components/survey/EligibilityStep";
import { PersonalDataStep, PersonalData, personalDataSchema } from "@/components/survey/PersonalDataStep";
import { SuccessStep } from "@/components/survey/SuccessStep";
import { GoogleFormStep } from "@/components/survey/GoogleFormStep";
import { DeclinedStep } from "@/components/survey/DeclinedStep";
import { supabase } from "@/integrations/supabase/client";
import { generateTrackingCode } from "@/lib/tracking-code";

type Stage =
  | "consent"
  | "eligibility"
  | "personal"
  | "googleForm"
  | "success"
  | "declined";
type DeclinedReason = "consent" | "age" | "location" | "criteria";

const STORAGE_KEY = "uniftc-glp1-survey-v2";
const STEPS = ["Termo", "Critérios", "Dados", "Google Forms", "Fim"];

interface FormState {
  stage: Stage;
  personal: Partial<PersonalData>;
  consent?: ConsentData;
  declinedReason?: DeclinedReason;
  trackingCode?: string;
}

const initial: FormState = {
  stage: "consent",
  personal: {},
};

const Index = () => {
  const [state, setState] = useState<FormState>(initial);
  const [personalValid, setPersonalValid] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  // Limpar progresso antigo para evitar cache de etapas anteriores
  useEffect(() => {
    localStorage.removeItem(STORAGE_KEY);
  }, []);

  // Scroll ao topo ao mudar de etapa
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, [state.stage]);

  const stepNumber = useMemo(() => {
    switch (state.stage) {
      case "consent":
        return 1;
      case "eligibility":
        return 2;
      case "personal":
        return 3;
      case "googleForm":
        return 4;
      case "success":
      case "declined":
        return 5;
    }
  }, [state.stage]);

  const goTo = (stage: Stage) => setState((s) => ({ ...s, stage }));

  const savePersonalDataAndOpenGoogleForm = async () => {
    const personalCheck = personalDataSchema.safeParse(state.personal);
    if (!personalCheck.success) {
      toast.error("Verifique os dados pessoais");
      goTo("personal");
      return;
    }

    setSubmitting(true);
    const trackingCode = state.trackingCode || generateTrackingCode();
    setState((s) => ({ ...s, trackingCode }));

    // Register the token as valid BEFORE allowing the user into Google Forms.
    // This is what makes "only the code generated by the system" actually work:
    // any code typed in the Forms is later checked against this list.
    const { data: registered, error: regError } = await supabase.rpc("register_tracking_code", {
      _code: trackingCode,
    });
    if (regError || !registered) {
      console.error("Falha ao registrar token", regError);
      toast.error("Não foi possível liberar a pesquisa. Tente novamente.");
      setSubmitting(false);
      return;
    }

    toast.success("Pesquisa liberada. Pode responder o Google Forms.");
    goTo("googleForm");

    supabase.from("survey_responses").insert({
        full_name: state.consent?.participantName || "Não informado",
        age: personalCheck.data.age,
        city: personalCheck.data.city,
        state: personalCheck.data.state,
        gender: personalCheck.data.gender,
        email: personalCheck.data.email || null,
        tracking_code: trackingCode,
        screening_answers: {
          electronic_consent: {
            participant_name: state.consent?.participantName || null,
            identity_document: state.consent?.identityDocument || null,
            consent_city: state.consent?.consentCity || null,
            consent_date: state.consent?.consentDate || null,
            accepted_tcle: true,
          },
        },
        main_answers: {},
        consent_given: true,
      }).then(({ error }) => {
        if (error) {
          console.error(error);
          toast.error("A pesquisa abriu, mas houve erro ao salvar os dados iniciais.");
        }
      }).then(() => {
        setSubmitting(false);
      });
  };

  const restart = () => {
    localStorage.removeItem(STORAGE_KEY);
    setState({ ...initial });
  };

  const renderStage = () => {
    switch (state.stage) {
      case "consent":
        return (
          <ConsentStep
            onAccept={(consent) =>
              setState((s) => ({ ...s, consent, stage: "eligibility" }))
            }
            onDecline={() =>
              setState((s) => ({ ...s, stage: "declined", declinedReason: "consent" }))
            }
          />
        );
      case "eligibility":
        return (
          <EligibilityStep
            onEligible={() => goTo("personal")}
            onIneligible={(reason) =>
              setState((s) => ({ ...s, stage: "declined", declinedReason: reason }))
            }
          />
        );
      case "personal":
        return (
          <PersonalDataStep
            data={state.personal}
            onChange={(d) => setState((s) => ({ ...s, personal: d }))}
            onValidityChange={setPersonalValid}
          />
        );
      case "googleForm":
        return <GoogleFormStep personal={state.personal} trackingCode={state.trackingCode} onDone={() => {
          localStorage.removeItem(STORAGE_KEY);
          goTo("success");
        }} />;
      case "success":
        return <SuccessStep onRestart={restart} />;
      case "declined":
        return <DeclinedStep onRestart={restart} reason={state.declinedReason} />;
    }
  };

  const showFooter = state.stage === "personal";

  const canAdvance = () => {
    if (state.stage === "personal") return personalValid;
    return true;
  };

  const handleNext = () => {
    if (!canAdvance()) {
      toast.error("Responda todos os campos obrigatórios para continuar");
      return;
    }
    if (state.stage === "personal") savePersonalDataAndOpenGoogleForm();
  };

  const handleBack = () => {
    if (state.stage === "personal") goTo("eligibility");
  };

  return (
    <div className="min-h-screen bg-gradient-soft">
      {/* Header */}
      <header className="sticky top-0 z-30 bg-background/85 backdrop-blur-md border-b border-border/60">
        <div className="max-w-2xl mx-auto px-4 py-3">
          <div className="flex items-center gap-2 mb-3">
            <div className="h-9 w-9 rounded-xl bg-gradient-primary flex items-center justify-center shadow-soft">
              <Stethoscope className="h-5 w-5 text-primary-foreground" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground leading-none">
                UNIFTC · Pesquisa Acadêmica
              </p>
              <h1 className="text-sm font-bold text-foreground truncate">
                Pesquisa GLP-1 & Estética
              </h1>
            </div>
          </div>
          <Stepper current={stepNumber} steps={STEPS} />
        </div>
      </header>

      {/* Conteúdo */}
      <main className="max-w-2xl mx-auto px-4 py-5 pb-32">{renderStage()}</main>

      {/* Footer fixo de navegação */}
      {showFooter && (
        <footer className="fixed bottom-0 inset-x-0 z-30 bg-background/95 backdrop-blur-md border-t border-border/60 shadow-elevated">
          <div className="max-w-2xl mx-auto px-4 py-3 flex gap-2">
            <Button
              variant="outline"
              size="lg"
              onClick={handleBack}
              disabled={submitting}
              className="h-12 rounded-xl px-4"
            >
              <ArrowLeft className="h-4 w-4" />
              <span className="hidden xs:inline ml-1">Voltar</span>
            </Button>
            <Button
              size="lg"
              onClick={handleNext}
              disabled={submitting}
              className="h-12 rounded-xl flex-1 bg-gradient-primary font-semibold"
            >
              Continuar
              <ArrowRight className="h-4 w-4 ml-2" />
            </Button>
          </div>
        </footer>
      )}
    </div>
  );
};

export default Index;
