CREATE OR REPLACE FUNCTION public.register_tracking_code_from_response()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.tracking_code IS NULL OR NEW.tracking_code !~ '^UFTC-[A-Z0-9]{4,16}$' THEN
    RAISE EXCEPTION 'invalid tracking code';
  END IF;

  INSERT INTO public.valid_tokens (code, is_active, notes)
  VALUES (NEW.tracking_code, true, 'auto-generated by site')
  ON CONFLICT (code) DO NOTHING;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.register_tracking_code_from_response() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.register_tracking_code_from_response() TO service_role;

DROP TRIGGER IF EXISTS register_tracking_code_on_response ON public.survey_responses;
CREATE TRIGGER register_tracking_code_on_response
BEFORE INSERT ON public.survey_responses
FOR EACH ROW
EXECUTE FUNCTION public.register_tracking_code_from_response();

REVOKE ALL ON FUNCTION public.register_tracking_code(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.register_tracking_code(text) TO service_role;

REVOKE ALL ON FUNCTION public.confirm_response_with_token(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.confirm_response_with_token(text) TO service_role;

REVOKE ALL ON FUNCTION public.mark_google_form_completed(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.mark_google_form_completed(text) TO service_role;

REVOKE ALL ON FUNCTION public.validate_and_consume_token(text, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.validate_and_consume_token(text, uuid) TO service_role;